### ISSUE TITLE
libxls reports "failed to decode utf16"

### ISSUE THREAD

**Issue by Bool2020** [libxls/libxls#115]
When I try to open a xls file which was encoded with Unicode (Big Endian) with some wide characters like Chinese, I got the "failed to decode utf16" error since unicode_decode  return 0x0. Here are the stack: 

Thread 13 "xxx" hit Breakpoint 1, unicode_decode (s=0xb4e0e132 "6e\366N\272N#", len=8, pWB=0xaf9f0c70) at xlstool.c:369
369	xlstool.c: No such file or directory.
(gdb) i s
#0  unicode_decode (s=0xb4e0e132 "6e\366N\272N#", len=8, pWB=0xaf9f0c70) at xlstool.c:369
#1  0xb62aaf94 in xls_appendSST (pWB=0xaf9f0c70, buf=0xb4e0de28 "\003", size=795) at xls.c:229
#2  0xb62aac18 in xls_addSST (pWB=0xaf9f0c70, sst=0xb4e0de20, size=803) at xls.c:146
#3  0xb62ad948 in xls_parseWorkBook (pWB=0xaf9f0c70) at xls.c:924
#4  0xb62af770 in xls_open_ole (ole=0xaacd1ea0, charset=0xb6ee2818 "UTF-8", outError=0xae5fc8e4) at xls.c:1468
#5  0xb62af8d8 in xls_open_file (file=0xaf9106c0 "/www/js/i18n/zh-CN/new_string-zh-CN (3).xls", charset=0xb6ee2818 "UTF-8", 
    outError=0xae5fc8e4) at xls.c:1498
#6  0xb6eb4744 in xxx(strLang=..., strXLSFileToMerge=..., strPathToMerge=..., strRsp=...)
    at xxx.cpp:767
#7  0x005506a0 in ?? ()
#8  0xb6eb754c in callback_handler (connection=0xaf0537f8, message=0xaf6d5f50, user_function_data=0xaf3fd180)
    at LG4_dbus_primitives.cpp:442
#9  0xb6d24ce4 in dbus_connection_dispatch () from /lib/libdbus-1.so.3
#10 0xb62de24c in ?? () from /lib/libdbus-glib-1.so.2
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) n
377	in xlstool.c
(gdb) fin
Run till exit from #0  unicode_decode (s=0xb4e0e132 "6e\366N\272N#", len=8, pWB=0xaf9f0c70) at xlstool.c:377
0xb62aaf94 in xls_appendSST (pWB=0xaf9f0c70, buf=0xb4e0de28 "\003", size=795) at xls.c:229
229	xls.c: No such file or directory.
Value returned is $23 = 0x0
(gdb) c
Continuing.

**Comment by Bool2020** [comment]
When I change the xls file charset into "Unicode (utf-8)" the same thing happens.

**Comment by evanmiller** [comment]
Can you share an XLS file that demonstrates the issue?

**Comment by FaradayChar** [comment]
Hi, I don't know which platform you use for. I change the local encoder .65001 as 936 to match with Chinese on Windows
